title: Kwabena Addo, Data Analyst
logo: /assets/images/kaddo.jpg
description: Data Analytics portfolio of Kwabena Addo, Hessen, Germany.
show_downloads: false
#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
   
