title: Kwabena Addo, Data Scientist
logo: /assets/images/kwabena_mugshot.jpg
description: Data Science Portfolio of Kwabena Addo, Data Scientiest based in Hessen, Germany.
show_downloads: true
#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
   
